name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  artifact:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
      - id: prep
        run: |
          echo "::set-output name=logdna-cloudwatch-version::v2.2.1"

      - uses: robinraju/release-downloader@v1.3
        with:
          repository: logdna/logdna-cloudwatch
          tag: ${{ steps.prep.outputs.logdna-cloudwatch-version }}
          fileName: logdna-cloudwatch.zip

      - run: |
          key=src/logdna-cloudwatch/${{ steps.prep.outputs.logdna-cloudwatch-version }}.zip
          aws s3 cp --acl public-read logdna-cloudwatch.zip "s3://infra.restyled.io/$key"

      - if: ${{ github.ref == 'refs/heads/main' }}
        uses: restyled-io/gitops-deploy-action@main
        with:
          token: ${{ secrets.GITOPS_ACCESS_TOKEN }}
          parameter-name: LogDNACloudWatchVersion
          parameter-value: ${{ steps.prep.outputs.logdna-cloudwatch-version }}
          committer-name: Restyled Commits
          committer-email: commits@restyled.io
          repository: restyled-io/ops
          stacks: cg-app/stacks/*/*/mgmt/forward-logs.yaml
