name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
      - uses: actions/checkout@v1
      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn install
      - run: |
          rm .env.test # Force use of CI env
          yarn test

  artifact:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
      - uses: actions/checkout@v1
      - run: yarn run dist
      - id: artifact
        run: |
          key=src/forward-logs/${{ github.sha }}.zip
          aws s3 cp --acl public-read dist/lambda.zip "s3://infra.restyled.io/$key"
          echo "::set-output name=key::$key"

    outputs:
      key: ${{ steps.artifact.outputs.key }}

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [test, artifact]
    runs-on: ubuntu-latest
    steps:
      - uses: restyled-io/gitops-deploy-action@main
        with:
          token: ${{ secrets.GITOPS_ACCESS_TOKEN }}
          parameter-name: FunctionSourceKey
          parameter-value: ${{ needs.artifact.outputs.key }}
          committer-name: Restyled Commits
          committer-email: commits@restyled.io
          repository: restyled-io/ops
          stacks: cg-app/stacks/*/*/mgmt/forward-logs.yaml
